apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/fofanaabou/catalog-service/k8s?ref=master

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/fofanaabou/catalog-service
  newTag: cd84ecdcc9abce38c5d8fa7ccd03166813d59840

replicas:
- count: 2
  name: catalog-service
