apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  template:
    spec:
      containers:
        - name: order-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging, test-data
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            requests:
              memory: "1Gi"  # Request 1 GB of memory
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "500m"